name: Use Monorepo Action (PR)

on:
  pull_request:
    branches: [main]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action A from monorepo
        uses: tri-actions/custom-actions/actions/get-aws-credentials@main
        with:
          account-id: '123456789012'
          region: 'us-east-1'
          federated-role-name: 'GHAFederatedRole'
          target-role-name: 'DefaultCrossAccountRole'

